enabled:
    RubinBank: true
    WorldGuard: true
MySQL:
    Host:
        Address: localhost
        User: user
        Password: password
        Database: RubinBank
        Table_Users: RubinBank
        Table_Bankomats: Bankomats
        Table_TriggerButtons: Buttons
        Table_AccountStatements: Actions
Currency:
    Name:
        Major:
            Singular: Rubin
            Plural: Rubins
        Minor:
            Singular: Gold
            usePlural: true
            Plural: of Gold
    Major:
        ItemID: 388
    Minor:
        ItemID: 266
WorldGuardOptions:
    limitToRegionWithParent: RubinBankAgency
    commandsLimitedToRegion: [create, payin, payout] #options: "create" (an account), "payin", "payout", "amount", "all"