enabled:
    RubinBank: true
    WorldGuard: true
MySQL:
    Host:
        Address: localhost
        User: user
        Password: password
        Database: RubinBank
        Table_Users: Users
        Table_Accounts: Accounts
        Table_Bankomats: Bankomats
        Table_TriggerButtons: Buttons
        Table_AccountStatements: Statements
Currency:
    Name:
        Major:
            Singular: Rubin
            Plural: Rubine
        Minor:
            Singular: Goldbarren
            usePlural: false
            Plural: Goldbarren
    Major:
        ItemID: 388 # Emerald
    Minor:
        ItemID: 266 # Gold Ingot
WorldGuardOptions:
    limitToRegionWithParent: RubinBankAgency
    commandsLimitedToRegion: [create, payin, payout] #options: "create" (an account), "payin", "payout", "amount", "all"