enabled:
    RubinBank: true
    WorldGuard: true
MySQL:
    Host:
        Address: localhost
        User: user
        Password: password
        Database: RubinBank
        Table: RubinBank
Currency:
    Name:
        Major:
            Singular: Rubin
            Plural: Rubins
        Minor:
            Singular: Gold
            usePlural: true
            Plural: of Gold
    Major:
        ItemID: 388
    Minor:
        ItemID: 266
        ratio100: false #if true use ratio 1/100. Default is 1/10.
WorldGuardOptions:
    limitToRegionWithParent: RubinBankAgency
    commandsLimitedToRegion: [create, payin, payout] #options: "create" (an account), "payin", "payout", "amount", "all"