enabled: true
MySQL:
    Host:
        Address: localhost
        User: user
        Password: password
        Database: RubinBank
        Table: RubinBank
        #Do not create the table! The Plugin will create it.
Currency:
    Name:
        Major:
            Singular: Rubin
            Plural: Rubins
        Minor:
            Singular: Gold
            usePlural: true
            Plural: of Gold
    Major:
        ItemID: 388
    Minor:
        ItemID: 266
        ratio100: false #if true use ratio 1/100. Default is 1/10.
GlobalSpawn:
    use: true #teleport to Global Spawn if world have no set Spawnpoint.
    set: false # do NOT change this value if x,y,z and world not set! The Plugin will change it automatically. Use command /setglobalspawn.
    x:
    y:
    z:
    world:
#Bankomat:
#    Item:
#        Up:
#            ID: 288
#        Down:
#            ID: 280