name: RubinBank
main: RubinBank.RubinBank
version: pre-20082012
commands:
    rubinbank:
        description: RubinBank Dummy-Command
        usage: /rubinbank
        permission: RubinBank.dummy
        permission-message: You need the RubinBank.dummy Permission to do this.
    error:
        description: Error Command
        usage: /error