name: RubinBank
main: RubinBank.RubinBank
version: pre-20082012
commands:
    rubinbank:
        description: RubinBank Dummy-Command
        usage: /rubinbank
        permission: RubinBank.dummy
        permission-message: Du brauchst die Berechtigung "RubinBank.dummy".
    error:
        description: Error Command
        usage: /error
    playerdetail:
        description: Set a Player Detail.
        usage: /pd <Detail> <Value>
        permission: RubinBank.Playerdetail;
        permissions-message: Du hast keine Berechtigung deine PlayerDetails zu bearbeiten.
        aliases: pd
    yaw:
        description: Return Players Yaw.
