name: RubinBank
main: RubinBank.RubinBank
version: pre-2012103
commands:
    rubinbank:
        description: RubinBank Dummy-Command
        usage: /rubinbank
        permission: RubinBank.dummy
        permission-message: Du brauchst die Berechtigung fuer "RubinBank.dummy".
        aliases: rb
    error:
        description: Error Command
        usage: ERROR
    playerdetail:
        description: Set a Player Detail.
        usage: /pd <Detail> <Value>
        permission: RubinBank.Playerdetail;
        permissions-message: Du brauchts die Berechtigung "RubinBank.Playerdetail".
        aliases: pd
    yaw:
        description: Return Players Yaw.
    tools:
        description: Return tools.
    bankomats:
        description: Return all Bankomats.
    mysql:
        description: Dummy Command f\u00FCr MySQL Datenbank
        permission: RubinBank.dummy.MySQL
        permission-message: Du brauchst die Berechtigung fuer "RubinBank.dummy.MySQL".
    account:
        description: Manage your Account
        permission: RubinBank.account
        permission-message: Du brauchst die Berechtigung fuer "RubinBank.account".
    rain:
       description: Toggle Rain or Storm
       permission: RubinBank.rain
    lastlog:
       description: See last Login(s)
       permission: RubinBank.lastlog
       permission-message: Du brauchst die Berechtigung fuer "RubinBank.lastlog".